services:
  infinity:
    image: michaelf34/infinity:${INFINITY_TAG:-latest}
    container_name: ${INFINITY_CONTAINER_NAME:-infinity-container}
    ports:
      - "${HOST_PORT:-7997}:7997"
    volumes:
      - ./cache:/app/.cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      v2
      --model-id ${INFINITY_MODEL_NAME:-BAAI/bge-m3}
      --port ${HOST_PORT:-7997}
volumes:
  infinity_data:
    name: ${INFINITY_VOLUME_NAME:-infinity_volume}
